# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Amarnath/Desktop/CRUISE_CONTROL_SYSTEM/CruiseControlSystem/CruiseControlSystem.cache/wt [current_project]
set_property parent.project_path C:/Users/Amarnath/Desktop/CRUISE_CONTROL_SYSTEM/CruiseControlSystem/CruiseControlSystem.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Amarnath/Desktop/CRUISE_CONTROL_SYSTEM/CruiseControlSystem/CruiseControlSystem.srcs/sources_1/new/CruiseControl.v
synth_design -top CruiseControl -part xc7k70tfbv676-1
write_checkpoint -noxdef CruiseControl.dcp
catch { report_utilization -file CruiseControl_utilization_synth.rpt -pb CruiseControl_utilization_synth.pb }
